services:
  jenkins-controller:
    image: jenkins/jenkins:jdk17
    container_name: jenkins-controller
    restart: on-failure
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  jenkins-agent:
    image: jenkins/inbound-agent:jdk17
    container_name: jenkins-agent
    restart: on-failure
    user: root
    environment:
      - JENKINS_URL=http://jenkins-controller:8080
      - JENKINS_AGENT_NAME=agent-1
      - JENKINS_SECRET=${JENKINS_AGENT_SECRET}
      - JENKINS_AGENT_WORKDIR=/home/jenkins
    depends_on:
      - jenkins-controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins:
    name: jenkins
    driver: bridge